# canal
version: '3.5'
services:
  canal-server:
    image: canal/canal-server:v1.1.6
    container_name: canal-server
    restart: always
    ports:
      - "11111:11111"
    volumes:
      - /docker/docker-compose/canal/conf/example:/home/admin/canal-server/conf/example
      - /docker/docker-compose/canal/conf/canal.properties:/home/admin/canal-server/conf/canal.properties
      - /docker/docker-compose/canal/logs:/home/admin/canal-server/logs
    privileged: true
    network_mode: "bridge"