global:
  resolve_timeout: 5m
  smtp_from: '2357191256@qq.com'
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_auth_username: '2357191256@qq.com'
  smtp_auth_password: ''
  smtp_require_tls: false
route:
  group_by: ['alertname']
  group_wait: 60s
  group_interval: 60s
  repeat_interval: 5m
  receiver: 'email'
receivers:
  - name: 'email'
    email_configs:
      - to: '2357191256@qq.com'
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

