version: "3.1"
services:
  seata-server:
    image: seataio/seata-server:1.5.2
    container_name: seata-server
    ports:
      - "7091:7091"
      - "8091:8091"
    environment:
      TZ: Asia/Shanghai
      STORE_MODE: db
      SEATA_IP: 127.0.0.1 # 配置为外网ip
      SEATA_PORT: 8091
    volumes:
      - /docker/docker-compose/seata/resources:/seata-server/resources
      - /docker/docker-compose/seata/logs/:/seata-server/logs
    network_mode: "bridge"