# 可参考： https://hub.docker.com/_/mysql
version: '3'
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql8.0                                      # 容器名为'mysql8.0'
    restart: unless-stopped                                               # 指定容器退出后的重启策略为始终重启，但是不考虑在Docker守护进程启动时就已经停止了的容器
    volumes:                                                      # 数据卷挂载路径设置,将本机目录映射到容器目录
      - "/docker/docker-compose/mysql8.0/my.cnf:/etc/mysql/my.cnf"
      - "/docker/docker-compose/mysql8.0/data:/var/lib/mysql"
      - "/docker/docker-compose/mysql8.0/conf.d:/etc/mysql/conf.d"
      - "/docker/docker-compose/mysql8.0/mysql-files:/var/lib/mysql-files"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root         # 设置root用户密码
      MYSQL_DATABASE: test               # 初始化的数据库名称
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true
    ports:                              # 映射端口
      - "3306:3306"
    network_mode: "bridge"
