version: '3'
services:
  sentinel-dashboard:
    image: bladex/sentinel-dashboard
    container_name: sentinel-dashboard
    restart: always
    environment:
      JAVA_OPTS: "-Dserver.port=8718 -Dcsp.sentinel.dashboard.server=8.142.156.127:8718 -Dproject.name=sentinel-dashboard"
    ports: #避免出现端口映射错误，建议采用字符串格式 8080端口为Dockerfile中EXPOSE端口
      - "8718:8718"
      - "8858:8858"
    volumes:
      - /docker/docker-compose/sentinel:/root/logs
    network_mode: "bridge"